SELECT * FROM EMPLOYEES_VIEW
WHERE SALARY >= 1000 AND GENDER = 0

SELECT * FROM MONTHLY_REPORT

SELECT * FROM COOK_BOOK 
WHERE INGREDIANT_NAME = 'Домати'

SELECT MENUS.MENU_TYPE, PRODUCTS.NAME FROM MENUS
JOIN PRODUCTS ON PRODUCTS.MENU_ID = MENUS.ID ORDER BY MENUS.MENU_TYPE

SELECT * FROM INGREDIANTS WHERE STORAGE_ID = 1009 AND PRICE >= 1