--cook book--
select prod.NAME, ing.NAME, iip.INGREDIANT_AMOUNT
from INGREDIANTS_IN_PRODUCTS iip
join INGREDIANTS ing on ing.ID=iip.INGREDIANT_ID
join  PRODUCTS prod on prod.ID=iip.PRODUCT_ID
order by prod.NAME

--table bill--
select ord.ID, ord.CREATED_AT, ord.FINISHED_AT,prod.NAME, prod.PRICE as PRICE_FOR_ONE, pio.AMOUNT as AMOUNT_IN_ORDER, prod.PRICE*pio.AMOUNT as PRICE_OF_ALL
from PRODUCTS_IN_ORDERS pio
join ORDERS ord
on ord.CREATED_AT > '2020-05-10 00:00:00' and ord.FINISHED_AT< '2020-05-10 23:59:59' and ord.ID=pio.ORDER_ID
join PRODUCTS prod on prod.ID=pio.PRODUCT_ID 
order by ord.ID
--union all--

--tomatoes consumption of every order--
select pio.ORDER_ID, SUM(iip.INGREDIANT_AMOUNT)AS KG_OF_TOMATOES
from PRODUCTS_IN_ORDERS pio
join
INGREDIANTS_IN_PRODUCTS iip
on pio.PRODUCT_ID=iip.PRODUCT_ID and iip.INGREDIANT_ID=20
GROUP BY pio.ORDER_ID
order by ORDER_ID


SELECT PIO.ORDER_ID, PROD.NAME, PIO.AMOUNT
FROM PRODUCTS_IN_ORDERS PIO
JOIN PRODUCTS PROD
ON PIO.PRODUCT_ID=PROD.ID
ORDER BY ORDER_ID
--NAME OF PRODUCT IN ORDERS

SELECT 
EMPLOYEES.FIRST_NAME,
EMPLOYEES.LAST_NAME,
EMPLOYEES.AGE,
EMPLOYEES.SALARY,
EMPLOYEES.AGE,
OCCUPATIONS.OCCUPATION_NAME
FROM EMPLOYEES
JOIN OCCUPATIONS on OCCUPATIONS.ID = EMPLOYEES.OCCUPATION_ID