SELECT AMOUNT, NAME
FROM INGREDIANTS
WHERE AMOUNT<3 
ORDER BY AMOUNT ASC;

SELECT AMOUNT, NAME
FROM INGREDIANTS
WHERE AMOUNT>4 AND GETDATE() >= DATEADD(DAY,-4,EXPIRES_AT)

SELECT SALARY, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY>999;

SELECT FIRST_NAME, LAST_NAME, EXPERIENCE_IN_YEARS
FROM EMPLOYEES
ORDER BY EXPERIENCE_IN_YEARS desc;

SELECT INGREDIANT_ID ,VALID_TO
FROM INGREDIANTS_PRICES
ORDER BY VALID_TO desc;