SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE OCCUPATION_ID IN (SELECT ID FROM OCCUPATIONS WHERE OCCUPATION_NAME = 'Главен-Готвач') ORDER BY FIRST_NAME;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE ID IN (SELECT EMPLOYEE_ID FROM ORDERS) ORDER BY FIRST_NAME;
SELECT PRODUCTS.NAME, PRODUCTS.PRICE FROM PRODUCTS WHERE MENU_ID IN (SELECT ID FROM MENUS WHERE IS_ACTIVE = 1) ORDER BY PRICE;
SELECT PRODUCTS.NAME, PRODUCTS.PRICE FROM PRODUCTS WHERE MENU_ID IN (SELECT ID FROM MENUS WHERE MENU_TYPE = 'Алкохолни напитки') ORDER BY PRICE;
SELECT INGREDIANTS.NAME, INGREDIANTS.PRICE FROM INGREDIANTS WHERE INGREDIANTS.STORAGE_ID IN (SELECT ID FROM STORAGES WHERE STORAGES.TYPE = 'Месо') ORDER BY PRICE;